

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_in_the_sack.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MoviesEntities1 : DbContext
{
    public MoviesEntities1()
        : base("name=MoviesEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Movy> Movies { get; set; }

}

}

