
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_in_the_sack.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Table
{

    public int Id { get; set; }

    public string Genre { get; set; }

    public string Title { get; set; }

    public int IsWatched { get; set; }

}

}
